#!/bin/sh

t=`basename $0`

cat > $t.I <<\EOF
#if (FOO)
# error ick
#else this is non-ansi
#endif so is this
EOF

cat > $t.EO <<\EOF
EOF

cat > $t.Ee <<\EOF
cppi: standard input: line 3: text following `#else' violates ANSI standard
cppi: standard input: line 4: text following `#endif' violates ANSI standard
EOF

options='-c --ansi'
expected_status=1

. $srcdir/test-common
