#!/bin/sh

t=`basename $0`

cat > $t.I <<\EOF
#if 1
# if 0
#  define x y
# endif  (ansi violation)
#endif
EOF

cat > $t.EO <<\EOF
EOF

cat > $t.Ee <<\EOF
cppi: standard input: line 4: text following `#endif' violates ANSI standard
EOF

options='-c --ansi'
expected_status=1

. $srcdir/test-common
