#!/bin/sh

t=`basename $0`

cat > $t.I <<\EOF
#if 1
# if 0
#  define x y
# endif  // PROFILE_SYNCH_REQUIRED     ^^^TRUE
#endif
EOF

cat > $t.EO <<\EOF
EOF

cat > $t.Ee <<\EOF
EOF

options='-c --ansi'
expected_status=0

. $srcdir/test-common
