#!/bin/sh

t=`basename $0`

cat > $t.I <<\EOF
#else
EOF

cat > $t.EO <<\EOF
#else
EOF

cat > $t.Ee <<\EOF
cppi: standard input: line 1: found #else without matching #if
EOF

expected_status=2

. $srcdir/test-common
