#!/bin/sh

t=`basename $0`

cat > $t.I <<\EOF
#elif(FOO)
EOF

cat > $t.EO <<\EOF
#elif (FOO)
EOF

cat > $t.Ee <<\EOF
cppi: standard input: line 1: found #elif without matching #if
EOF

expected_status=2

. $srcdir/test-common
