#!/bin/sh

t=`basename $0`

cat > $t.I <<\EOF
#ifdef(FOO)
EOF

cat > $t.EO <<\EOF
#ifdef(FOO)
EOF

cat > $t.Ee <<\EOF
cppi: standard input: line 1: unterminated #ifdef
EOF

expected_status=2

. $srcdir/test-common
