#!/bin/sh

t=`basename $0`

cat > $t.I <<\EOF
#ifndef(FOO)
EOF

cat > $t.EO <<\EOF
#ifndef (FOO)
EOF

cat > $t.Ee <<\EOF
cppi: standard input: line 1: unterminated #ifndef
EOF

expected_status=2

. $srcdir/test-common
