#!/bin/sh

t=`basename $0`

cat > $t.I <<\EOF
int c = '\"';
# if(FOO)
# endif
EOF

cat > $t.EO <<\EOF
int c = '\"';
#if (FOO)
#endif
EOF

cat > $t.Ee <<\EOF
EOF

expected_status=0

. $srcdir/test-common
