#!/bin/sh

t=`basename $0`

cat > $t.I <<\EOF
#if(FOO)
#elif(NO_BLANK_AFTER_ELIF)
#error
#endif
EOF

cat > $t.EO <<\EOF
#if (FOO)
#elif (NO_BLANK_AFTER_ELIF)
# error
#endif
EOF

cat > $t.Ee <<\EOF
EOF

options=
expected_status=0

. $srcdir/test-common
