#!/bin/sh

t=`basename $0`

cat > $t.I <<\EOF
#if (FOO)
#elif (NO_BLANK_AFTER_ELIF)
# undef FOOBAR
#endif
EOF

cat > $t.EO <<\EOF
EOF

cat > $t.Ee <<\EOF
EOF

options=-c
expected_status=0

. $srcdir/test-common
